<project xmlns="http://maven.apache.org/POM/4.1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>lingo.project.pro</groupId>
    <artifactId>lingo-project-pro</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>


    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/>
    </parent>
    <modules>
        <module>lingo-backend</module>
    </modules>

    <profiles>
        <profile>
            <id>lingo-frontend</id>
            <modules>
                <module>lingo-frontend</module>
            </modules>
        </profile>
    </profiles>

</project>