spring:
  application:
    name: lingo-backend
  datasource:
    url: jdbc:postgresql://localhost:1506/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/changelog.json
